### ISSUE TITLE
Add option to ignore stdin data

### ISSUE THREAD

**Issue by zapman449** [httpie/cli#150]
```
http: error: Request body (from stdin or a file) and request data (key=value) cannot be mixed.
```

This error is rather cryptic.  I'm writing a shell script to interact with a rest API, and I'm doing this:

```
http --output subnet --pretty format --form post "${URLHOST}subnets" "cidr=${cidr}" "name=${name}" "description=${name}" "availabilityZoneId=${az}" "networkId=${VPCid}" "$ACCESSKEY" "$SECRETKEY" "$ACCOUNTID" "_providerId=aws" "_regionId=${REGION}"
```

Which produces (when preceded by 'echo' a command that works perfectly well.  However, this version gives the error in the subject.

Am I being stupid, or is this something else?

FYI: The result of the above is as followed (sanitized slightly)

```
http --output subnet --pretty format --form post https://test.grid.domain.com/subnets cidr=10.124.33.128/25 name=Load_balancers description=Load_balancers availabilityZoneId=us-east-1c networkId=vpc-31433e7e x-gridauth-accesskey:DOYOUNEEDTOKNOW x-gridauth-secretaccesskey:WHATISWITHALLTHEQUESTIONS x-gridauth-accountid:11223344556677 _providerId=aws _regionId=us-east-1
```

**Comment by CrazyPython** [comment]
This is very confusing, and goes against httpie being able to work anywhere. Using such a command inside a bash loop is a very common application. Httpie should not complain when key/value is given and it receives stdin: instead letting key/value dominate.

**Comment by sigmavirus24** [comment]
> Httpie should not complain when key/value is given and it receives stdin: instead letting key/value dominate.

That maybe is intuitive to you, but to many others the exact opposite is far more intuitive. Because tooling should not try to guess, it is far better to raise an error and provide you an escape hatch if you feel you know better, which this does.

**Comment by jenstroeger** [comment]
I ran into this issue when using httpie inside of a function passed to [GNU parallel](https://www.gnu.org/software/parallel/):
```bash
function call_api {
    local FOO=`http --json --auth $TOKEN: post $HOST/api/foo name="Ţẽṧẗ" < /dev/tty | python3 -c "import json,sys;obj=json.load(sys.stdin);print(obj['result']['id']);"`
    […]
}

export -f call_api
export HOST=…
export TOKEN=…
parallel --env HOST --env TOKEN ::: call_api call_api call_api call_api call_api
```
Thanks to the [above comment](https://github.com/jakubroztocil/httpie/issues/150#issuecomment-21419373) the parallel function invocation works now. Leaving this comment here for future reference 😊

**Comment by sgoll** [comment]
For future reference, there now is a CLI argument `--ignore-stdin` that can be used to explicitly tell HTTPie that request data (key=value) should be preferred over request body (from stdin).

```
http --ignore-stdin http://… lorem=ipsum dolor=sit
```

Cf. https://github.com/jakubroztocil/httpie#16redirected-input

**Comment by rcorre** [comment]
Encountered this while using `http` in a for loop. It worked fine locally, but failed in gitlab. `--ignore-stdin` resolved it.

**Comment by NightMachinary** [comment]
I tried redirecting stdin to null `</dev/null`, but it made httpie behave weird. Why's that? I mean, shouldn't there be a way to make a command ignore stdin from the shell itself?

**Comment by jakubroztocil** [comment]
@NightMachinary you want to use the `--ignore-stdin` option. That’s how you tell HTTPie to not read `STDIN`.

```bash
$ echo 'this STDIN data is ignored'  |  http  --ignore-stdin POST httpbin.org/post hello=world
```

**Comment by NightMachinary** [comment]
@jakubroztocil I know that, I am saying if `http` did not have `--ignore-stdin`, how could we eliminate stdin going to `http` from the shell itself?

**Comment by jakubroztocil** [comment]
@NightMachinary tou cannot eliminate `STDIN` (and the other standard streams), but you close it:

```bash
$ echo ignored data | http httpbin.org/anything 0<&-
```

**Comment by jakubroztocil** [comment]
@NightMachinary  and redirecting `/dev/null` is a bit different:

```
$ http httpbin.org/anything < /dev/null
```

This is invokes HTTPie with an open & redirected `STDIN`, so HTTPie will read it and end up with an empty string, which it will then happily use as the request body data (effectively defaulting to `POST`), unless you tell it not to with `--ignore-stdin`. 

So it’s basically equivalent to this:

```
$ echo -n | http httpbin.org/anything 
```
