### ISSUE TITLE
## Acceptance Criteria

### ISSUE THREAD

**Issue by jpmaniqis** [httpie/cli#1561]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [x] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

_Originally posted by @jpmaniqis in https://github.com/mdn/content/issues/32272_

_Originally posted by @jpmaniqis in https://github.com/mdn/content/issues/32274_

**Comment by Ousret** [comment]
Please refrain yourself from posting complete unrelated things to HTTPie.
This create too much noise.
