### ISSUE TITLE
it is not possible install for arm linux 

### ISSUE THREAD

**Issue by AndriySidliarskiy** [httpie/cli#1562]
## Checklist

- [x] I've searched for similar issues.
- [x] I'm using the latest version of HTTPie.

---

## Minimal reproduction code and steps

1. curl -SsL https://packages.httpie.io/deb/KEY.gpg | gpg --dearmor -o /usr/share/keyrings/httpie.gpg && \
     echo "deb [arch="arm64" signed-by=/usr/share/keyrings/httpie.gpg] https://packages.httpie.io/deb ./" > /etc/apt/sources.list.d/httpie.list && \
     apt update && apt install httpie

## Current result
exit code 1
…

## Expected result
installed tools
…

---

**Comment by siddharth07-ui** [comment]
HI, I am trying to create a conda environment with Python version3.8 and trying to run this code inside it. I am getting the below error:

====================================================================================
curl -SsL https://packages.httpie.io/deb/KEY.gpg | gpg --dearmor -o /usr/share/keyrings/httpie.gpg &&
echo "deb [arch="arm64" signed-by=/usr/share/keyrings/httpie.gpg] https://packages.httpie.io/deb ./" > /etc/apt/sources.list.d/httpie.list &&
apt update && apt install httpie
File '/usr/share/keyrings/httpie.gpg' exists. Overwrite? (y/N) y
gpg: can't create '/usr/share/keyrings/httpie.gpg': Permission denied
gpg: no valid OpenPGP data found.
gpg: dearmoring failed: Permission denied
curl: (23) Failed writing body
====================================================================================

I tried the below command and seems I am able to install httipe version 3.2.1. Can you please try it and let me know.
====================================================================================
curl -SsL https://packages.httpie.io/deb/KEY.gpg | sudo gpg --dearmor -o /usr/share/keyrings/httpie.gpg && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/httpie.gpg] https://packages.httpie.io/deb ./" | sudo tee -a /etc/apt/sources.list.d/httpie.list && sudo apt update && sudo apt upgrade httpie

Output --
http --version
3.2.1
====================================================================================

**Comment by AndriySidliarskiy** [comment]
@siddharth07-ui but you use arch=amd64 in my case arch=arm64 it`s two different architecures.

**Comment by siddharth07-ui** [comment]
Yes, I have tried both the arch's as you can see, and just thought of sharing my results with you.

**Comment by Ousret** [comment]
The installation tutorial has been updated it seems. For anyone stumbling here and still facing this or similar issue, ping us.
The gpgarmor was missing privilege elevation via sudo.
