### ISSUE TITLE
Please add support for Mise

### ISSUE THREAD

**Issue by Blackjacx** [httpie/cli#1563]
[Mise](https://github.com/jdx/mise) is a modern and powerful dev-tool installer and version manager and builds on top of [asdf](https://github.com/asdf-vm/asdf). It would be really cool if you could add `httpie-cli` to its registry so all people out there can instal it using this version manager ❤️

Under the hood it uses asdf's plugin system.

The description or the plugin registry can be foud [here](https://github.com/mise-plugins) and the plugin registry repo itself [here](https://github.com/mise-plugins/registry).

[Here](https://asdf-vm.com/plugins/create.html) is the guide for how to create an asdf plugin.

**Comment by Ousret** [comment]
Unfortunately it is unlikely that the owner will spend time trying to register HTTPie at every possible place.
I understand the need for certain individual, but it tends to multiply the maintenance burden.

The most likely outcome is that one of you submit a proposal to that particular registry. We can answer any question if you stumble upon a blocker, but it should go fine.

regards,
