### ISSUE TITLE
unable to CONTRIBUTING

### ISSUE THREAD

**Issue by darkb0ts** [httpie/cli#1571]
## Checklist

- [x] I've searched for similar feature requests.
 Yes 
---

## Enhancement request

…

---

## Problem it solves

```
$ make test
\n\n\033[0;32m### Running tests ### \033[0m\n
venv/bin/python -m pytest 
process_begin: CreateProcess(NULL, venv/bin/python -m pytest, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:107: test] Error 2
(venv)
Admin@Hellbat MINGW64 /d/Open Source Contribution/cli (fixing/prasanna)
$ make all
\n\n\033[0;32m### Uninstalling httpie ### \033[0m\n
venv/bin/pip3 uninstall --yes httpie &2>/dev/null
/usr/bin/sh: line 1: venv/bin/pip3: No such file or directory
Verifyingâ€¦
cd .. && ! venv/bin/python -m httpie --version &2>/dev/null
/usr/bin/sh: line 1: venv/bin/python: No such file or directory
Done

\n\n\033[0;32m### Updating package tools ### \033[0m\n
venv/bin/pip3 install --upgrade pip wheel build
process_begin: CreateProcess(NULL, venv/bin/pip3 install --upgrade pip wheel build, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:53: install-reqs] Error 2
```

---

## Additional information, screenshots, or code examples
$ python --version
Python 3.12.2
…

**Comment by Ousret** [comment]
You may have missed a step in preparing your development environment.

Try the following commands:

```
$ python -m pip install --upgrade pip wheel
$ python -m pip install --upgrade '.[dev]'
$ python -m pytest --verbose ./httpie ./tests
```

If this does not help, try to start off a clean environment and redo the provided steps.

I can confirm that HTTPie pipelines work as of today.

**Comment by darkb0ts** [comment]
> You may have missed a step in preparing your development environment.
> 
> Try the following commands:
> 
> ```
> $ python -m pip install --upgrade pip wheel
> $ python -m pip install --upgrade '.[dev]'
> $ python -m pytest --verbose ./httpie ./tests
> ```
> 
> If this does not help, try to start off a clean environment and redo the provided steps.
> 
> I can confirm that HTTPie pipelines work as of today.

thank for that. but already fix that.
