### ISSUE TITLE
### Summary

### ISSUE THREAD

**Issue by jpmaniqis** [httpie/cli#1572]
### Summary

As per the announcement, [learning lab was deprecated](https://github.blog/changelog/2022-09-01-deprecating-learning-lab/). 
However, the learning lab URL (https://lab.github.com/) is still available but leads to a 404 error page. 

You might want to redirect this to https://skills.github.com/.

### How to reproduce

1. Go to https://lab.github.com/.
2. See 404 error.

<img src="https://github.com/skills/introduction-to-github/assets/23019147/c3fa988f-7204-425f-8614-2c883dd85528" alt="screenshot of 404 error when you go to github learning lab" />

_Originally posted by @dipikabh in https://github.com/skills/introduction-to-github/issues/682_

**Comment by Ousret** [comment]
Please refrain yourself from posting complete unrelated things to HTTPie.
This create too much noise.
