### ISSUE TITLE
please    provide support for scoop  download   

### ISSUE THREAD

**Issue by Super1Windcloud** [httpie/cli#1604]
when  I  use  scoop  install httpie  on powershell7  

![image](https://github.com/user-attachments/assets/76223ddf-5525-4cd8-897d-f0d4ab17cef7)
![image](https://github.com/user-attachments/assets/523010e6-dae3-411e-907b-640bfb417423)

**Comment by AchilleasTsiamoulis** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
