### ISSUE TITLE
SSLError on HTTPie. Directly using Requests works.

### ISSUE THREAD

**Issue by edufelipe** [httpie/cli#204]
I'm getting SSL errors when connecting to some sites using HTTPie. When I manually connect to them using `requests` the error does not manifest itself.

```
$ http 'https://app.onsign.tv/accounts/login/'
http: error: SSLError: [Errno bad handshake] [('SSL routines', 'SSL23_GET_SERVER_HELLO', 'sslv3 alert handshake failure')]

$ python
Python 2.7.5 (default, Aug 25 2013, 00:04:04)
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> r = requests.get('https://app.onsign.tv/accounts/login/')
>>> r.status_code
200

$ pip freeze
Pygments==1.6
httpie==0.8.0
requests==2.2.1
wsgiref==0.1.2
```

**Comment by njbraun** [comment]
If someone runs into this, performing the following fixes it:

```shell
sudo apt-get install libffi-dev
pip install pyOpenSSL ndg-httpsclient pyasn1
```

https://github.com/kennethreitz/requests/issues/2022#issuecomment-143348232

**Comment by k0pernikus** [comment]
I was also having the an error like this:

    http: error: SSLError: [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]

and google led me here. In my case I just forgot that I had a self-signed certificate, so adding `--verify no` argument made the call work.

There may be a hidden feature request inside here, namely: Making the error message a bit more human readable.
