### ISSUE TITLE
Integers are passed as strings when using URL parameters (==)

### ISSUE THREAD

**Issue by sackdan** [httpie/cli#211]
When passing integers as URL parameter, HTTPie always considers the value as a string.
Example:
http -v POST http://localhost:1010/api string=="access_token" integer==23245

When checking in my API, the "integer" value is passed as a string.
If I make the request by hand using DEV HTTP CLIENT, for example, the integer is passed as an integer and not as a string. Note that in HTTPie output the integer is displayed without quotes.

**Comment by aop4** [comment]
https://devhints.io/httpie
You can use :=, like so:
`http POST localhost:8080/places streetAddress="121 Lindbergh Rd" zip:=14324`

**Comment by AdilKhurshid** [comment]
how to pass int64 value for golang ?
