### ISSUE TITLE
Add an --insecure / -k option to disable SSL certificate verification

### ISSUE THREAD

**Issue by ghost** [httpie/cli#226]
When testing https to a test machine that has a self-signed certificate, it is handy to be able to disable certificate verification.

```
$ http https://192.168.4.137/test

http: error: SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:547)
```

vs:

```
$ curl --insecure https://192.168.4.137/test
... got what I was expecting here ...
```

**Comment by wendersonferreira** [comment]
I'm receive this error, but my certificate is valid! any idea? Thanks!

**Comment by zeknox** [comment]
It would be nice if the the utility also accepted `--verify=false`

**Comment by jakubroztocil** [comment]
@zeknox that is also accepted:

https://github.com/jakubroztocil/httpie/blob/aae596d4724b39d3ad0da0ef4d6a5e7eb98ae418/httpie/client.py#L230-L235

Does it not work for you?
