### ISSUE TITLE
Support for cookies?

### ISSUE THREAD

**Issue by Govinda-Fichtner** [httpie/cli#26]
Is there support for cookies?

The underlying request lib seems to support cookies....

Cheers,

Govinda

**Comment by mcnemesis** [comment]
@jakubroztocil I'm wondering if cookies set by the server can be persisted across calls? Is this possible at all in httpie? So that for example I can use this to test session-based api calls...

**Comment by jakubroztocil** [comment]
@mcnemesis Yes, there [sessions](https://github.com/jakubroztocil/httpie#sessions) feature that allows cookies as well as custom headers and auth to persist between requests.

**Comment by mcnemesis** [comment]
Awesome! Thanks @jakubroztocil

**Comment by dufferzafar** [comment]
@jkbrzt Is it possible to send multiple cookies?

I tried: `http http://httpbin.org/cookies 'Cookie:doo=dar' 'Cookie:foo=bar'`

But I only get one cookie!

```
HTTP/1.1 200 OK
Content-Length: 40
Content-Type: application/json
Date: Wed, 03 Aug 2016 11:43:35 GMT

{
    "cookies": {
        "foo": "bar"
    }
}
```

**Comment by NightMachinary** [comment]
@jakubroztocil Can we use json input for setting cookies?

**Comment by jakubroztocil** [comment]
@NightMachinary you can use a session file (https://httpie.org/docs#sessions):


## Using `cookies`
```bash
$ cat  my-session.json
```

```json
{
    "cookies": {
        "MOODLEID1_": {
            "value": "%250xxx5C2"
        },
        "MoodleSession": {
            "value": "btsmxxxxxxxosn7"
        }
    },
}
```

```bash
$ http --session ./my-session.json httpbin.org/headers
```

```http
GET / HTTP/1.1
Cookie: MOODLEID1_=%250xxx5C2; MoodleSession=btsmxxxxxxxosn7
```

---

## Using `headers`

```bash
$ cat  my-session.json
```

```json
{
    "headers": {
        "Cookie": {
            "MOODLEID1_=%250xxx5C2; MoodleSession=btsmxxxxxxxosn7"
        }
    }
}
```

```bash
$ http --session ./my-session.json httpbin.org/headers
```

```http
GET / HTTP/1.1
Cookie: MOODLEID1_=%250xxx5C2; MoodleSession=btsmxxxxxxxosn7
```

**Comment by faaizajaz** [comment]
```
{
    "headers": {
        "Cookie": {
            "MOODLEID1_=%250xxx5C2; MoodleSession=btsmxxxxxxxosn7"
        }
    }
}
```


I get an invalid JSON error with the above. it expects a colon and value as it is treating those cookies as a key

**Comment by BoboTiG** [comment]
@faaizajaz, please open a specific issue.

**Comment by faaizajaz** [comment]
@BoboTiG Happy to do so. Just wanted to confirm that if I have a session file containing only the block I shared above, should it work, or am I missing something about how sessions work?
