### ISSUE TITLE
Can't send POST request with multiple files

### ISSUE THREAD

**Issue by drgomesp** [httpie/cli#267]
I'm trying this:

```
http -f POST http://localhost:8000/products/images files\[\]@B497A_1.jpg files\[\]@B497A_2.jpg
```

But the request only contains the last file.

Do we have support for multiple files yet?

**Comment by wordyallen** [comment]
Hello,

I couldn't find the syntax for this is the doc.

```shell
http -f post localhost:3090/api/lots photos@[/]200.png photos@[/]300.png
```

this didn't work. 

Thanks,
Joe

**Comment by jkbrzt** [comment]
@wordyallen 

```bash
http -f :3090/api/lots  photos@200.png  photos@300.png
```

(Please create a new issue if you are still having an issue with the syntax.)

**Comment by wordyallen** [comment]
wow. thanks!

**Comment by benoitjupille** [comment]
Is this working for you ?

For me this syntax is working : 

`http -f :3090/api/lots  photos[]@200.png  photos[]@300.png`

**Comment by mwauer** [comment]
Is this still working for anybody? I can't get it to work with any of the above syntax. Running in the HTTPie demo:
`$ echo a > a.txt
$ echo b > b.txt
$ http -f httpbin.org/post files@a.txt files@b.txt
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: close
Content-Length: 360
Content-Type: application/json
Date: Thu, 13 Jun 2019 16:22:56 GMT
Server: gunicorn/19.9.0

{
    "args": {},
    "data": "",
    "files": {
        "files": "a\n"
    },
    "form": {},
    "headers": {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate",
        "Connection": "keep-alive",
        "Content-Length": "302",
        "Content-Type": "multipart/form-data; boundary=44226e711ad05c462d7c07d70d67c925",
        "Host": "httpbin.org",
        "User-Agent": "HTTPie/1.0.0"
    },
    "json": null,
    "origin": "127.0.0.1",
    "url": "http://httpbin.org/post"
}

$`
