### ISSUE TITLE
'--verify no' still yields a certificate error

### ISSUE THREAD

**Issue by srgvg** [httpie/cli#32]
When testing an ssl enabled url, with a self signed certificatie, using the '--verify no' option still yields an error:

serge@phenicia:~$ http -t get https://url
[Errno 1] _ssl.c:503: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
serge@phenicia:~$ http -t --verify no get https://url
[Errno 185090050] _ssl.c:340: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib

**Comment by jmn** [comment]
Hi - I'm seeing this - --verify=no has no effect. using version 0.9.9. 
https://github.com/httpie/httpie-http2 is installed.
