### ISSUE TITLE
httpie output has lots of additional characters on windows

### ISSUE THREAD

**Issue by obmarg** [httpie/cli#36]
Running `http GET httpie.org` on windows results in a load of extra characters being printed out:

```
HTTP/1.1 ←[39;49;00m←[34m302←[39;49;00m←[33m Found←[39;49;00m
Date:←[39;49;00m←[33m Mon, 19 Mar 2012 15:13:17 GMT←[39;49;00m
Server:←[39;49;00m←[33m Apache←[39;49;00m
X-Awesome:←[39;49;00m←[33m Thanks for trying HTTPie :)←[39;49;00m
Location:←[39;49;00m←[33m https://github.com/jkbr/httpie←[39;49;00m
Cache-Control:←[39;49;00m←[33m max-age=1800←[39;49;00m
Expires:←[39;49;00m←[33m Mon, 19 Mar 2012 15:43:17 GMT←[39;49;00m
Content-Length:←[39;49;00m←[33m 214←[39;49;00m
Content-Type:←[39;49;00m←[33m text/html; charset=iso-8859-1←[39;49;00m

←[36m<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">←[39;49;00m
←[34;01m<html←[39;49;00m←[34;01m>←[39;49;00m←[34;01m<head←[39;49;00m←[34;01m>←[39;49;00m
←[34;01m<title←[39;49;00m←[34;01m>←[39;49;00m302 Found←[39;49;00m←[34;01m</title>←[39;49;00m
←[34;01m</head>←[39;49;00m←[34;01m<body←[39;49;00m←[34;01m>←[39;49;00m
←[34;01m<h1←[39;49;00m←[34;01m>←[39;49;00mFound←[39;49;00m←[34;01m</h1>←[39;49;00m
←[34;01m<p←[39;49;00m←[34;01m>←[39;49;00mThe document has moved ←[39;49;00m←[34;01m<a←[39;49;00m ←[39;49;00m←[36mhref=←[39;49;00m←[33m"https://github.com/jkbr/httpie"←[39;49;00m←[34;01m>←[39;49;00mhere←[39;49;00m←[34;01m</a>←[39;49;00m.←[39;49;00m←[34;01m</p>←[39;49;00m
```

I'm guessing that these are escape codes that provide the colored output on other operating systems.  Running `http -u GET httpie.org` results in correct (though monochrome) output.

It'd be nice to get cross platform colored output like provided by [clint](https://github.com/kennethreitz/clint/).

**Comment by mykwillis** [comment]
I'm not sure if there was a regression of if there is some problem with my local terminal, but the most recent version is showing this behavior for me. 

>python --version
Python 3.4.3

>http --version
0.9.2
←[0m

>http httpie.org
←[38;5;33mHTTP←[39m←[38;5;245m/←[39m←[38;5;37m1.1←[39m←[38;5;245m ←[39m←[38;5;37m302←[39m←[38;5;245m ←[39m←[38;5;136mFound←[39m
←[38;5;245mConnection←[39m←[38;5;245m:←[39m←[38;5;245m ←[39m←[38;5;37mclose←[39m
←[38;5;245mContent-Length←[39m←[38;5;245m:←[39m←[38;5;245m ←[39m←[38;5;37m292←[39m
[...]

**Comment by bryanbak** [comment]
I just installed this on windows and am having the same issue as @mykwillis, but only in powershell. If I use httpie in the regular cmd prompt it looks fine.

Windows 7
python 2.7.10
httpie 0.9.2

**Comment by mykwillis** [comment]
I notice that if I 

    pip install colorama==0.3.2

as opposed to using the latest colorama (0.3.3), then I don't get the control characters in the output.

It's not in color, but at least it's not garbled.

So this is likely something to do with a change in colorama between 0.3.2 and 0.3.3

**Comment by bryanbak** [comment]
Just downgraded colorama to 0.3.2 based on @mykwillis suggestion and powershell output looks much better now. Thanks for the advice!
