### ISSUE TITLE
enable quic protocol

### ISSUE THREAD

**Issue by sunisdown** [httpie/cli#523]
Httpie will support [QUIC](https://github.com/google/proto-quic) protocol?

**Comment by jpbochi** [comment]
http/3 and quic are picking up speed.

- cURL has some implementations: https://github.com/curl/curl/blob/master/docs/HTTP3.md
- NGINX has beta support: https://www.nginx.com/blog/our-roadmap-quic-http-3-support-nginx/
- AWS CloudFront just introduced support for it: https://aws.amazon.com/blogs/aws/new-http-3-support-for-amazon-cloudfront/

Could httpie add support for http/3 before curl does?

**Comment by adriens** [comment]
> Could httpie add support for http/3 before curl does?

Hmm looks like a challenge :roll_eyes: :thought_balloon: ....

**Comment by Ousret** [comment]
It does not have to "support" any protocols, the underlying HTTP client has to.
If interested, it is now supported as an experimental version https://github.com/httpie/httpie/issues/1512

**Comment by Jiehong** [comment]
Http3 is now available in 30+% of websites: https://w3techs.com/technologies/details/ce-http3

Any news on supporting it?
