### ISSUE TITLE
Idea: create a separate curl2httpie tool

### ISSUE THREAD

**Issue by brasilikum** [httpie/cli#570]
My idea is simple:
Create a tool (e.g. curl2httpie) which accepts all the commands curl also does. 
It tries to parse a curl command with all options
- if it fails, by default it executes the command via curl
- if it succeeds,by default it prints out the corresponding httpie command
- by default, it runs the corresponding httpie command

It could be symlinked to `curl`, so any time you copy paste a curl command into your terminal, you learn how you would have achieved the same command with httpie plus you get all the benefits in output and so on of actually running httpie.

What do you think?
The reason I am asking here is to make sure I did not miss something like this if it already exists.
I would enjoy implementing this, but only if it does not exist yet.

**Comment by dcb9** [comment]
I have just implemented one, but the feature is very simple, stupid and incomplete. It's only convert curl command to httpie command.

```
$ curl2httpie curl -u user: github.com
http -a user: GET github.com
```

and there is a [curl2httpie online app](http://curl2httpie.online/) to do this.

welcome you to contributing!

**Comment by Ousret** [comment]
As it already does exists,
I am closing this one.
