### ISSUE TITLE
remove need for quotes to be escaped for raw json input

### ISSUE THREAD

**Issue by avisser** [httpie/cli#77]
While it may be intentional, it is quite unintuitive that you need to escape your quotes for raw json input

```
$> http POST localhost:8888/api/learn/license_check purchased_licenses:=["android.test.purchased"]
http: error: purchased_licenses:=[android.test.purchased] is not valid JSON
```

but

```
$> http POST localhost:8888/api/learn/license_check purchased_licenses:=[\"android.test.purchased\"]
HTTP/1.1 200 OK
...
```

This is in OSX terminal - 10.7.4.

**Comment by afolaran** [comment]
Hello.

I have just installed httpie and I am trying to perform some aggregate queries on a data base on my local machine. I got the error message; 

http-script.py: error: argument REQUEST_ITEM: "[" is not a valid value

What can I do to resolve this? I have tried several options but no success. Below I attach a screenshot of my console

![error page](https://cloud.githubusercontent.com/assets/16158966/12815788/34210182-cb51-11e5-9ce2-063b0bd134aa.png)
